start-at-login = true

after-startup-command = 'exec-and-forget ~/.config/mac-scripts/borders.sh'

exec-on-workspace-change = 'exec-and-forget sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 3
    inner.vertical =   3
    outer.left =       3
    outer.bottom =     3
    outer.top =        3
    outer.right =      3

[mode.main.binding]
    alt-enter = 'exec-and-forget ~/.config/mac-scripts/open_iterm2.sh'

    alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # use aerospace join-with over i3 split
    alt-c = 'join-with right'
    alt-v = 'join-with down'

    alt-f = 'fullscreen --no-outer-gaps'

    alt-s = 'layout v_accordion' # 'layout stacking' in i3
    alt-w = 'layout h_accordion' # 'layout tabbed' in i3
    alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3
    alt-d = 'balance-sizes'

    alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 0'
    alt-p = 'workspace P'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 0'
    alt-shift-p = 'move-node-to-workspace P'

    alt-shift-x = 'close --quit-if-last-window'

    alt-o = ['exec-and-forget ~/.config/mac-scripts/borders.sh monitor', 'mode monitor']
    alt-r = ['exec-and-forget ~/.config/mac-scripts/borders.sh resize',  'mode resize']
    alt-q = ['exec-and-forget ~/.config/mac-scripts/borders.sh service', 'mode service']

    # disable macos hide shit
    cmd-h = []
    cmd-alt-h = []

[workspace-to-monitor-force-assignment]
    P = 'built-in'

[mode.monitor.binding]
    h = ['focus-monitor left',  'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']
    j = ['focus-monitor down',  'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']
    k = ['focus-monitor up',    'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']
    l = ['focus-monitor right', 'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']

    shift-h = ['move-workspace-to-monitor left',  'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']
    shift-j = ['move-workspace-to-monitor down',  'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']
    shift-k = ['move-workspace-to-monitor up',    'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']
    shift-l = ['move-workspace-to-monitor right', 'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']

    esc = ['exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    esc = ['exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']

[mode.service.binding]
    esc = ['reload-config',           'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']
    q = ['enable toggle']
    r = ['flatten-workspace-tree',    'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main'] # reset layout
    f = ['layout floating tiling',    'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main'] # Toggle between floating and tiling layout

    alt-shift-h = ['join-with left',  'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']
    alt-shift-j = ['join-with down',  'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']
    alt-shift-k = ['join-with up',    'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']
    alt-shift-l = ['join-with right', 'exec-and-forget ~/.config/mac-scripts/borders.sh', 'mode main']
