#!/bin/sh

# Make sure this is before the 'exec' command or it won't be executed.
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

# Turn caps into escape
xmodmap -e 'clear Lock'
xmodmap -e 'keycode 0x42 = Escape'
xmodmap -e 'keycode 9 = Delete'

#set cursor
xsetroot -cursor_name left_ptr
#set xresources
xrdb -merge ~/.Xresources

#set wallpaper
sh ~/.fehbg

#bind keys
xbindkeys

#hide the mouse
hhp &

#start wm
exec xmonad
