#!/bin/sh

# Make sure this is before the 'exec' command or it won't be executed.
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

# Turn caps into escape
xmodmap -e 'clear Lock'
xmodmap -e 'keycode 0x42 = Escape'
xmodmap -e 'keycode 9 = Delete'

# set cursor
xsetroot -cursor_name left_ptr
# set xresources
xrdb -merge ~/.Xresources

# set wallpaper
sh ~/bin/fehbg

# hide the mouse
hhp &

# auto lock screen after inactivity or sleep
xautolock -time 10 -lockaftersleep -locker slimlock &

# enable redshift
redshift &

#start wm
exec i3
