.PHONY: default
default:
	mkdir -p ~/.config/mac-scripts
	ln -sf $(shell pwd)/open_iterm2.sh ~/.config/mac-scripts/open_iterm2.sh
	ln -sf $(shell pwd)/float_window.sh ~/.config/mac-scripts/float_window.sh
