.PHONY: default
default:
	mkdir -p ~/.config/i3
	ln -sf $(shell pwd)/config ~/.config/i3/config
	ln -sf $(shell pwd)/i3blocks.conf ~/.config/i3/i3blocks.conf
	ln -snf $(shell pwd)/scripts ~/.config/i3/scripts
	ln -sf $(shell pwd)/bg.jpg ~/.config/bg.jpg
