.PHONY: default
default:
	mkdir -p ~/.i3
	ln -sf $(shell pwd)/config ~/.i3/config
	ln -sf $(shell pwd)/i3blocks.conf ~/.i3/i3blocks.conf
	ln -snf $(shell pwd)/scripts ~/.i3/scripts
	ln -sf $(shell pwd)/bg.jpg ~/.config/bg.jpg
