.PHONY: default
default:
	mkdir -p ~/.config/i3
	ln -sf $(shell pwd)/config ~/.config/i3/config

	mkdir -p ~/.config/polybar
	ln -snf $(shell pwd)/polybar ~/.config/polybar/config
	ln -sf $(shell pwd)/launch_polybar.sh ~/.config/polybar/launch.sh
