export HISTFILE=$HOME/.zhistory
export HISTSIZE=100000
export SAVEHIST=100000
export HOSTNAME="`hostname`"
export PAGER='less'
export MANPAGER='less'
export EDITOR='vim'
export ALTERNATE_EDITOR='vim'
export LESS="-XFR"

# Created by `pipx` on 2023-12-07 00:49:18
export PATH="$PATH:/Users/choochootrain/.local/bin"
eval "$(mise activate zsh --shims)"

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :
