export HOSTNAME="`hostname`"
export PAGER='less'
export MANPAGER='less'
export EDITOR='vim'
export ALTERNATE_EDITOR='vim'
export LESS="-XFR"

if [[ -f '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]]; then
  source '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
  export NIX_PATH="$HOME/.nix-defexpr"
fi

export N_PREFIX="$HOME/.n"
export PATH="$PATH:$HOME/.bin:$N_PREFIX/bin"

export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="$PATH:/opt/homebrew/bin:/opt/homebrew/sbin";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

export GPG_TTY=$(tty)
