export PATH="/usr/local/bin:/usr/local/sbin/:/bin:/sbin:/usr/bin:/usr/sbin:$HOME/bin:$PATH"
export TZ="America/Los_Angeles"
export HISTFILE=$HOME/.zhistory
export HISTSIZE=1000
export SAVEHIST=1000
export HOSTNAME="`hostname`"
export PAGER='less'
export MANPAGER="/bin/sh -c \"col -bx | vim -c 'set ft=man' -R -M -\""
export EDITOR='vim'
export ALTERNATE_EDITOR='vim'
export PYTHONSTARTUP=~/.pyrc
export NODE_PATH=/bin:/usr/lib/node_modules
export MANPAGER="/bin/sh -c \"col -bx | vim -c 'set ft=man' -R -M -\""
export PYTHONSTARTUP=~/.pyrc
export LESS="-XFR"
