#!/bin/sh
IMG=$(ls -ltr ~/.config/wallpapers/* | shuf -n 1 | tr -s ' ' | cut -d ' ' -f 9)
feh --no-fehbg --bg-fill $IMG
printf '#%x%x%x' `convert $IMG -scale 1x1\! -format '%[fx:int(255*r)] %[fx:int(255*g)] %[fx:int(255*b)]' info:` > ~/.config/colorscheme/fg
